### ISSUE TITLE
Input hash

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#478]
Do this one after #479. In this one there is no need to hash anything, as the user is supposed to provide their own sha256 hash. This should however be verified (that the input appears to be a valid hash).

![image](https://user-images.githubusercontent.com/1344105/220620712-b6b131e8-0164-4f6a-b48a-0affe8901bdd.png)

**Comment by ba1ciu** [comment]
@PiranavanShanmugavadivelu Let's go with this one next. So instead of getting hash from the webassembly operation, we just fetch it from the input field. As for the verification if it is a hash or not, we have to check if it's a byte array of size 32 that has been hex encoded to string. Probably checking with a regex like this is going to be easiest:
```js
\b[A-Fa-f0-9]{64}\b
```
