### ISSUE TITLE
String to hash

### ISSUE THREAD

**Issue by gjermundgaraba** [EmpowerPlastic/empowerchain#511]
Add another option to the certify tabs called "String".

This tab should use a text field to take in a string and hash it using the webassembly function we used for the file (see #479 and #509).

![image](https://user-images.githubusercontent.com/1344105/220621031-fc20ae5a-79b5-4fc5-b8ff-3a684971ba9e.png)

**Comment by gjermundgaraba** [comment]
FYI @hasikam, this needs design for how the text field should look (it should be a multiline text area)

**Comment by gjermundgaraba** [comment]
@hasikam, did you add designs for this or no?

**Comment by ba1ciu** [comment]
Let's base on the design for a hash tab:
![image](https://user-images.githubusercontent.com/39089377/232435477-643215f9-e661-48ef-be6b-4d1ad64e3812.png)

But instead of having a single line input, let's do a multiline input box and in place of the `Input the SHA256 checksum...` text, use:
`You can input arbitrary plain text below to create a proof of it's existence.`

Register button should be changed to `Create proof` like in the `File` tab.

Between text box and button, we should add 2 checkboxes:

- [ ] include whitespace characters (spaces, tabs, new lines, etc.)

- [ ] include letter casing

If non of the checkboxes are checked, text from the input should be trimmed of every whitespace character and all the letters should be lowercased before calculating sha256sum. If checkboxes are checked, then respectively we should skip the transformations.

Finally, calculated hash should be send to blockchain like in `File` case and success screen should be presented.

FYI @PiranavanShanmugavadivelu
